parameters:

  - name: Deploy_ResourceGroup
    type: boolean
    default: "true"

  - name: Deploy_FunctionApp
    type: boolean
    default: "true"

  - name: Deploy_FunctionApp_Configuration
    type: boolean
    default: "true"

trigger: none
pr: none

resources:
  repositories:
    - repository: VMAutomationRepo
      type: 'github'
      name: 'CloudInfra-App-Toolbox'
      endpoint: 'Automation_githubconnection'
      ref: $(Build.SourceBranch)

variables:

  - name: 'Deploy_ResourceGroup'
    value: ${{ parameters.Deploy_ResourceGroup}}

  - name: Deploy_FunctionApp
    value: ${{ parameters.Deploy_FunctionApp}}

  - name: Deploy_FunctionApp_Configuration
    value: ${{ parameters.Deploy_FunctionApp_Configuration}}

  - name: group_vars
    value: VariableGroup

  - name: template_vars
    value: ../../variables/pipeline-vars.yaml

  - name: azure_sub
    value: CloudAppConnection

  - name: agent_name
    value: Deploy Agent 

stages:

  - stage: Deploy_Infrastructure
    jobs:
      - job: Deploy_Infrastructure
        displayName: "Infrastructure Deployment"
        pool:          
          name: ${{ variables.agent_name }}
        variables:
          - template: ${{ variables.template_vars }}
          - group: ${{ variables.group_vars }}
        steps:
          - template: ./templates/release.yaml
            parameters:
              azureSubscription: ${{ variables.azure_sub }}
