parameters:
  azureSubscription: ""

steps:

# For Resource Group TODO: If to deploy resource group, please make sure it conmment it out. 

- task: CreateResourceGroup@2
  displayName: 'prod-bb-resource-group-V2.0.1'
  inputs:
    var_subscriptionId: '$(var_subscriptionId)'
    var_location: '$(var_location)'
    var_deploymentId: '$(var_deploymentId)'
    var_owner: '$(var_owner)'
    var_chargeCode: '$(var_chargeCode)'
    var_productApp: '$(var_productApp)'
    var_resourceGroupName: '$(var_resourceGroupName)'
    var_environment: '$(var_environment)'
  condition: and(succeeded(), eq(variables['Deploy_ResourceGroup'], 'true'))